[package]
name = "atm"
edition = "2024"

[dependencies]
git2 = { version = "0.20", features = ["https", "ssh"] }
kairoi = "0.2.3"
tokio = { version = "1.47.1", features = ["full"] }
async-trait = "0.1.89"

[profile.release]
opt-level = 3
lto = "fat"
